# Generated by Django 5.1.6 on 2025-06-03 00:33

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('student', 'Estudiantes'), ('professor', 'Profesores')], default='student', help_text='Tipo de usuario reportado (ej: student o professor)', max_length=50)),
                ('users_info', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, choices=[('evidence', 'Evidencias'), ('request', 'Solicitudes'), ('defense_tribunal', 'Tribunal y defensa'), ('defense_act', 'Actas de defensa')], help_text='Lista de categorías reportadas', size=None)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
