# Generated by Django 5.1.6 on 2025-05-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defenses_tribunals', '0001_initial'),
        ('users', '0003_customuser_password_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensetribunal',
            name='tutor',
        ),
        migrations.AddField(
            model_name='defensetribunal',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='defense_tribunal_tutors', to='users.professor'),
        ),
        migrations.AlterField(
            model_name='defensetribunal',
            name='state',
            field=models.CharField(choices=[('A', 'Aprobado'), ('D', 'Desaprobado'), ('P', 'Pendiente'), ('I', 'Incompleto')], default='I', max_length=20),
        ),
    ]
