# Generated by Django 5.1.6 on 2025-05-21 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defenses_tribunals', '0002_remove_defensetribunal_tutor_defensetribunal_tutors_and_more'),
        ('users', '0003_customuser_password_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensetribunal',
            name='oponent',
        ),
        migrations.AddField(
            model_name='defensetribunal',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense_tribunal_opponent', to='users.professor'),
        ),
    ]
