# Generated by Django 5.1.6 on 2025-06-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defenses_tribunals', '0003_remove_defensetribunal_oponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensetribunal',
            name='selected_ece',
            field=models.CharField(choices=[('TD', 'Trabajo de diploma'), ('PF', 'Portafolio'), ('AA', 'Defensa de Artículos Científicos'), ('EX', 'Exhimición')], default='TD', max_length=20, verbose_name='Selected ECE'),
        ),
    ]
