# Generated by Django 5.1.6 on 2025-03-20 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_ece', models.CharField(choices=[('Tesis', 'Trabajo de diploma'), ('Portfolio', 'Portafolio'), ('Art Cient', 'Defensa de Artículos Científicos'), ('Exhibición', 'Exhibición')], default='Tesis', max_length=20, verbose_name='Selected ECE')),
                ('state', models.CharField(choices=[('Approved', 'Aprobada'), ('Disapproved', 'Desaprobada'), ('Pending', 'Pendiente')], default='Pending', max_length=20, verbose_name='State')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.student', verbose_name='Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
