# Generated by Django 5.1.6 on 2025-05-12 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('users', '0002_remove_professor_user_remove_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.student', verbose_name='Student'),
        ),
    ]
