# Generated by Django 5.1.6 on 2025-05-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_request_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='selected_ece',
            field=models.CharField(choices=[('Tesis', 'Trabajo de diploma'), ('Portafolio', 'Portafolio'), ('Art Cient', 'Defensa de Artículos Científicos'), ('Exhimición', 'Exhimición')], default='Tesis', max_length=20, verbose_name='Selected ECE'),
        ),
    ]
