# Generated by Django 5.1.6 on 2025-05-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_request_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='selected_ece',
            field=models.CharField(choices=[('TD', 'Trabajo de diploma'), ('PF', 'Portafolio'), ('AA', 'Defensa de Artículos Científicos'), ('EX', 'Exhimición')], default='TD', max_length=20, verbose_name='Selected ECE'),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('A', 'Aprobada'), ('D', 'Desaprobada'), ('P', 'Pendiente')], default='P', max_length=20, verbose_name='State'),
        ),
    ]
