# Generated by Django 5.1.6 on 2025-06-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_selected_ece_alter_request_state'),
        ('users', '0005_alter_professor_role_alter_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='users.student', verbose_name='Student'),
        ),
    ]
