# Generated by Django 5.1.6 on 2025-05-12 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='Description')),
                ('attachment_type', models.CharField(choices=[('URL', 'Url'), ('Archivo', 'File')], default='URL', max_length=20)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('student', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='users.student')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
