# Generated by Django 5.1.6 on 2025-03-20 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='Description')),
                ('attachment_type', models.CharField(choices=[('URL', 'Url'), ('Archivo', 'File')], default='URL', max_length=20)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='users.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainScienceField',
            fields=[
                ('field', models.CharField(choices=[('None', 'Ninguno'), ('Ingeniería de software y Programación', 'Software Engineering and Programming'), ('Inteligencia organizacional', 'Organizational Intelligence'), ('Tecnologías de la información', 'Information Technologies')], default='None', editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(choices=[('None', 'Ninguno'), ('Analista', 'Analyst'), ('Programador', 'Programmer'), ('Diseñador de Bases de Datos', 'Database Designer'), ('Diseñador de Pruebas', 'Test Designer'), ('Analista de Procesos de Negocio', 'Business Process Analyst'), ('Analista de Calidad', 'Quality Analyst'), ('Administrador de Bases de Datos', 'Database Administrator'), ('Administrador de Configuraciones', 'Configuration Administrator'), ('Soporte Técnico de Hardware y Software', 'Hardware and Software Technical Support'), ('Especialista en Seguridad Informática', 'Information Security Specialist'), ('Administrador de Redes', 'Network Administrator'), ('Arquitecto de Software', 'Software Architect'), ('Jefe de Proyecto', 'Project Leader')], default='None', editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Distinctions',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
            ],
            options={
                'abstract': False,
            },
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='FullScienceField',
            fields=[
                ('field', models.CharField(choices=[('None', 'Ninguno'), ('Representación y procesamiento de la información y del conocimiento:\n                                        modelación, estructura de datos, bases de datos, bases de conocimientos,\n                                        procesos algorítmicos o heurísticos, programación, técnicas de inteligencia\n                                        artificial', 'Representation and Information and Knowledge Processing: Modeling,\n                                        Data Structure, Databases, Knowledge Bases, Algorithmic or Heuristic Processes,\n                                        Programming, Artificial Intelligence Techniques'), ('Metodologías de desarrollo de software', 'Software Development Methodologies'), ('Modelos de desarrollo de software', 'Software Development Models'), ('Gestión de proyectos informáticos', 'Information Technology Project Management'), ('Reingeniería de procesos para la gestión de la información y el conocimiento y\n                                de investigación científica', 'Process Reengineering for Information and Knowledge\n                                Management and Scientific Research'), ('Diseño y/o administración de base de datos', 'Database Design and/or Administration'), ('Diseño de pruebas', 'Test Design'), ('Administración de la configuración', 'Configuration Administration'), ('Administración de la Calidad', 'Quality Administration'), ('Teoría de Sistemas', 'Systems Theory'), ('Teoría de la Información', 'Information Theory'), ('Inteligencia de negocios, proceso de desarrollo orientado a servicios,\n                                análisis y gestión de procesos de negocios, arquitectura empresarial', 'Business Intelligence,\n                                Service-Oriented Development Process, Business Process Analysis and Management, Enterprise Architecture'), ('Arquitectura de computadoras y redes, periféricos, interfaz de comunicación\n                                            hombremáquina, teleinformática y sistemas de operación.', 'Computer architecture\n                                            and networks, peripherals, human-machine communication interface, teleinformatics, and\n                                            operating systems.'), ('Seguridad y ética informática', 'Informatic security and ethics'), ('Administración de redes', 'Network Administration'), ('Soporte técnico de Software y Hardware', 'Hardware and Software Technical Support')], default='None', editable=False, primary_key=True, serialize=False)),
                ('main_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidences.mainsciencefield')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('roles', models.ManyToManyField(blank=True, related_name='projects', to='evidences.roles', verbose_name='Roles')),
            ],
            options={
                'abstract': False,
            },
            bases=('evidences.evidence',),
        ),
        migrations.CreateModel(
            name='ScientificArticle',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidences.evidence')),
                ('science_field', models.ManyToManyField(to='evidences.fullsciencefield')),
            ],
            options={
                'abstract': False,
            },
            bases=('evidences.evidence',),
        ),
    ]
