# Generated by Django 5.1.6 on 2025-05-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0002_alter_evidence_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='evidences/attachments/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='attachment_type',
            field=models.CharField(choices=[('url', 'Url'), ('file', 'File')], max_length=20),
        ),
    ]
