# Generated by Django 5.1.6 on 2025-06-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0003_alter_evidence_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='attachment_type',
            field=models.CharField(choices=[('url', 'URL'), ('file', 'Archivo')], max_length=20),
        ),
    ]
