# Generated by Django 5.1.6 on 2025-06-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0004_alter_evidence_attachment_type'),
        ('users', '0005_alter_professor_role_alter_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='users.student'),
        ),
    ]
