# Generated by Django 5.1.6 on 2025-06-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0005_alter_evidence_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
