# Generated by Django 5.1.6 on 2025-03-20 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseAct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(upload_to='defense_acts/attachments/')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='defense_acts', to='users.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
