# Generated by Django 5.1.6 on 2025-03-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defense_acts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defenseact',
            options={'ordering': ['id']},
        ),
    ]
