# Generated by Django 5.1.6 on 2025-06-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense_acts', '0003_defenseact_author'),
        ('users', '0005_alter_professor_role_alter_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defenseact',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='defense_act', to='users.professor'),
        ),
        migrations.AlterField(
            model_name='defenseact',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='defense_act', to='users.student'),
        ),
    ]
