# Generated by Django 5.1.6 on 2025-06-13 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_professor_role_alter_student_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_ece', models.CharField(choices=[('TD', 'Trabajo de diploma'), ('PF', 'Portafolio'), ('AA', 'Defensa de Artículos Científicos'), ('EX', 'Exhimición')], default='TD', max_length=20, verbose_name='Selected ECE')),
                ('state', models.CharField(choices=[('A', 'Aprobada'), ('D', 'Desaprobada'), ('P', 'Pendiente')], default='P', max_length=20, verbose_name='State')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='users.student', verbose_name='Student')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
