# Generated by Django 5.1.6 on 2025-03-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('None', 'Ninguno'), ('FTI', 'Facultad de Tecnologías Interactivas'), ('FTE', 'Facultad de Tecnologías Educativas'), ('CITEC', 'Facultad de Ciencias y Tecnologías Computacionales'), ('FTL', 'Facultad de Tecnologías Libres'), ('FCS', 'Facultad de Ciberseguridad'), ('FIO', 'Facultad de Información Organizacional')], default='None', max_length=50),
        ),
    ]
