# Generated by Django 5.1.6 on 2025-05-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_professor_user_remove_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
