# Generated by Django 5.1.6 on 2025-06-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_professor_id_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='role',
            field=models.CharField(choices=[('professor', 'Profesor'), ('dptoInf', 'Departamento de Informática'), ('decan', 'Decano')], default='professor', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('FTI', 'Facultad de Tecnologías Interactivas'), ('FTE', 'Facultad de Tecnologías Educativas'), ('CITEC', 'Facultad de Ciencias y Tecnologías Computacionales'), ('FTL', 'Facultad de Tecnologías Libres'), ('FCS', 'Facultad de Ciberseguridad'), ('FIO', 'Facultad de Información Organizacional')], max_length=50),
        ),
    ]
